// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024142628_SeedVillaToDB")]
    partial class SeedVillaToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A luxurious villa featuring a private pool, ocean view, and premium amenities.",
                            ImageUrl = "/images/villa1.jpg",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A modern beachfront villa with stunning sea views and direct beach access.",
                            ImageUrl = "/images/villa2.jpg",
                            Name = "Beachfront Paradise",
                            Occupancy = 6,
                            Price = 300.0,
                            sqft = 700
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A peaceful villa in the mountains with panoramic views and fresh air.",
                            ImageUrl = "/images/villa3.jpg",
                            Name = "Mountain Retreat",
                            Occupancy = 3,
                            Price = 180.0,
                            sqft = 480
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An elegant villa located in the city center with modern interiors and rooftop access.",
                            ImageUrl = "/images/villa4.jpg",
                            Name = "City Deluxe Suite",
                            Occupancy = 4,
                            Price = 250.0,
                            sqft = 600
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beautifully designed villa in a desert setting with private spa and pool.",
                            ImageUrl = "/images/villa5.jpg",
                            Name = "Desert Oasis",
                            Occupancy = 4,
                            Price = 220.0,
                            sqft = 520
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A tranquil lakeside villa perfect for relaxation and fishing enthusiasts.",
                            ImageUrl = "/images/villa6.jpg",
                            Name = "Lakeview Escape",
                            Occupancy = 4,
                            Price = 190.0,
                            sqft = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
